function spatialIndex = createSpatialIndex(terrain, cellSize)
%CREATESPATIALINDEX Create a bucketed exact nearest-neighbor index.

if nargin < 2 || isempty(cellSize) || cellSize <= 0
    cellSize = max(terrain.gridSpacing, 1);
end

domainWidth = max(terrain.maxX - terrain.minX, terrain.maxY - terrain.minY);
spatialIndex = struct( ...
    'cellSize', cellSize, ...
    'minX', terrain.minX, ...
    'minY', terrain.minY, ...
    'maxRing', ceil(domainWidth / cellSize) + 2, ...
    'buckets', containers.Map('KeyType', 'char', 'ValueType', 'any'));
end
